#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * Import mate-in-1/2/3 puzzles from the Lichess puzzle CSV.
 *
 * Usage:
 *   npm run import-puzzles -- path\to\lichess_db_puzzle.csv [count=1000]
 *
 * Lichess CSV columns:
 *   PuzzleId,FEN,Moves,Rating,RatingDeviation,Popularity,NbPlays,Themes,GameUrl,OpeningTags
 *
 * Notes about the Lichess format:
 *   - `FEN` is the position BEFORE the opponent's setup move.
 *   - The first move in `Moves` is played by the opponent; after that it's the
 *     player's turn and the remaining moves alternate.
 *
 * This importer:
 *   1. Picks puzzles tagged mateIn1 / mateIn2 / mateIn3.
 *   2. Applies the opponent's first move to get the starting FEN the player sees.
 *   3. Stores only the remaining moves.
 *   4. Sorts by rating and tries to balance across the three categories.
 *   5. Writes src/puzzles/puzzle-db.ts.
 *
 * CC0 data. See https://database.lichess.org/#puzzles for the download.
 */

import fs from "node:fs";
import path from "node:path";
import readline from "node:readline";
import { fileURLToPath, pathToFileURL } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function main() {
  const [, , csvArg, countArg] = process.argv;
  if (!csvArg) {
    console.error("Usage: npm run import-puzzles -- <path-to-lichess_db_puzzle.csv> [count=1000]");
    process.exit(1);
  }
  const csvPath = path.resolve(csvArg);
  const total = Math.max(30, Math.min(5000, parseInt(countArg ?? "1000", 10) || 1000));
  if (!fs.existsSync(csvPath)) {
    console.error(`CSV not found: ${csvPath}`);
    process.exit(1);
  }

  // Dynamic import of the engine helpers. We compile on the fly via tsx.
  const { parseFEN, parseUci, toFEN } = await import(
    pathToFileURL(path.join(__dirname, "..", "src", "engine", "board.ts")).href
  );
  const { makeMove, legalMovesFrom } = await import(
    pathToFileURL(path.join(__dirname, "..", "src", "engine", "rules.ts")).href
  );

  const perCategoryCap = Math.ceil(total / 3);
  const buckets: Record<1 | 2 | 3, any[]> = { 1: [], 2: [], 3: [] };

  const stream = fs.createReadStream(csvPath, { encoding: "utf8" });
  const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });
  let first = true;
  let scanned = 0;

  rl.on("line", (line) => {
    if (first) { first = false; return; } // skip header
    scanned++;
    const cols = line.split(",");
    if (cols.length < 8) return;
    const [PuzzleId, FEN, Moves, RatingS, , , , Themes] = cols;
    const themes = Themes.split(" ").filter(Boolean);
    const mateIn: 1 | 2 | 3 | null =
      themes.includes("mateIn1") ? 1 :
      themes.includes("mateIn2") ? 2 :
      themes.includes("mateIn3") ? 3 : null;
    if (!mateIn) return;
    if (buckets[mateIn].length >= perCategoryCap * 3) return; // gather extra for sort

    const moveList = Moves.split(" ");
    // Expected ply count: mateIn*2 - 1 (player is the last to move).
    // Lichess prefixes an opponent setup move, so total = 2*N.
    if (moveList.length !== mateIn * 2) return;

    try {
      const pre = parseFEN(FEN);
      const setup = parseUci(moveList[0]);
      const setupMove = legalMovesFrom(pre, setup.from).find(
        (m: any) => m.to.file === setup.to.file && m.to.rank === setup.to.rank &&
                    (!setup.promotion || m.promotion === setup.promotion)
      );
      if (!setupMove) return;
      const startState = makeMove(pre, setupMove);
      const startFen = toFEN(startState);
      const remaining = moveList.slice(1);
      buckets[mateIn].push({
        id: PuzzleId,
        fen: startFen,
        moves: remaining,
        themes: themes.filter((t: string) => t !== "mateIn1" && t !== "mateIn2" && t !== "mateIn3").slice(0, 3).concat([`mateIn${mateIn}`]),
        rating: parseInt(RatingS, 10) || undefined
      });
    } catch {
      // skip invalid
    }
  });

  await new Promise<void>((resolve) => rl.on("close", () => resolve()));

  // Sort each bucket by rating ascending (easy first) and trim.
  for (const n of [1, 2, 3] as const) {
    buckets[n].sort((a, b) => (a.rating ?? 9999) - (b.rating ?? 9999));
    buckets[n] = buckets[n].slice(0, perCategoryCap);
  }

  const out: any[] = [];
  for (const n of [1, 2, 3] as const) out.push(...buckets[n]);

  const outPath = path.join(__dirname, "..", "src", "puzzles", "puzzle-db.ts");
  const body = `// Auto-generated by scripts/import-puzzles.mjs from the Lichess puzzle DB (CC0).
// Do not edit by hand — run \`npm run import-puzzles -- <path-to-csv>\` to refresh.

export interface PuzzleRow {
  id: string;
  fen: string;
  moves: string[];
  themes: string[];
  rating?: number;
}

export const PUZZLE_DB: PuzzleRow[] = ${JSON.stringify(out, null, 2)};
`;
  fs.writeFileSync(outPath, body, "utf8");
  console.log(`Scanned ${scanned} rows. Wrote ${out.length} puzzles to ${path.relative(process.cwd(), outPath)}.`);
  console.log(`  mate-in-1: ${buckets[1].length}`);
  console.log(`  mate-in-2: ${buckets[2].length}`);
  console.log(`  mate-in-3: ${buckets[3].length}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
